[package]
name = "nf-engine"
version.workspace = true
edition.workspace = true

[dependencies]
libc = "0.2"
nf-protocol = { path = "../nf-protocol" }
nf-transport = { path = "../nf-transport" }
nf-arbitrator = { path = "../nf-arbitrator" }
nf-recovery = { path = "../nf-recovery" }
nf-testkit = { path = "../nf-testkit" }
